[application]
name = "Hotki"
resources = ["Info.plist"]

[bundle]
identifier = "com.hotki.app"
publisher = "Aldo Cortesi"

[bundle.macos]
files = {}
hardened_runtime = false


[web.app]
title = "hotki"
[web.resource]
style = []
script = []

[web.resource.dev]
script = []
